import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowUpRight, ArrowRight } from 'lucide-react';

// Hero photo is served as responsive WebP variants generated by scripts/optimize-hero.mjs.
// The original PNG (heri-atelier.png) remains as the source for the OG image template.

const HeroAtelier: React.FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start start', 'end start'],
  });

  // Photo stays solid through most of the hero, then fades out before the next section starts
  const photoOpacity = useTransform(scrollYProgress, [0, 0.7, 1], [1, 1, 0]);
  // Content fades a bit earlier so the headline lifts away while the photo lingers briefly
  const contentOpacity = useTransform(scrollYProgress, [0, 0.6, 0.9], [1, 1, 0]);
  const contentY = useTransform(scrollYProgress, [0, 1], ['0%', '15%']);

  const easeQuiet = [0.22, 0.61, 0.36, 1] as const;

  return (
    <section
      ref={containerRef}
      className="relative min-h-screen w-full overflow-hidden bg-navy flex items-end pt-32 md:pt-40"
    >
      {/* Ambient Ken Burns — bulletproof CSS keyframe (more pronounced + slight pan) */}
      <style>{`
        @keyframes hero-atelier-kenburns {
          0%   { transform: scale(1.0)  translate3d(0, 0, 0); }
          50%  { transform: scale(1.10) translate3d(-1.2%, 0.7%, 0); }
          100% { transform: scale(1.0)  translate3d(0, 0, 0); }
        }
      `}</style>

      {/* Fixed photo background — z-0; sections below the hero are wrapped in z-10 (App.tsx) so they paint above this. Fades out as hero scrolls past. */}
      <motion.div
        style={{ opacity: photoOpacity }}
        className="fixed inset-0 z-0 pointer-events-none overflow-hidden"
      >
        {/* Ken Burns layer — ambient slow zoom + tiny pan, CSS-driven so it never restarts */}
        <div
          className="absolute inset-0"
          style={{
            animation: 'hero-atelier-kenburns 22s ease-in-out infinite',
            willChange: 'transform',
          }}
        >
          <picture>
            <source media="(min-width: 1920px)" srcSet="/images/hero-2560.webp" type="image/webp" />
            <source media="(min-width: 1280px)" srcSet="/images/hero-1920.webp" type="image/webp" />
            <source media="(min-width: 768px)" srcSet="/images/hero-1280.webp" type="image/webp" />
            <img
              src="/images/hero-768.webp"
              alt=""
              fetchPriority="high"
              decoding="async"
              className="absolute inset-0 w-full h-full object-cover"
              style={{ filter: 'saturate(0.92) brightness(0.82) contrast(1.05)' }}
            />
          </picture>
        </div>

        {/* Bottom-up gradient to ground the headline */}
        <div
          className="absolute inset-0"
          style={{
            background:
              'linear-gradient(to top, rgba(10,22,40,0.92) 0%, rgba(10,22,40,0.65) 30%, rgba(10,22,40,0.15) 60%, rgba(10,22,40,0) 80%)',
          }}
        />
        {/* Subtle navy wash to keep the brand palette dominant */}
        <div className="absolute inset-0 bg-navy/15" />
      </motion.div>

      {/* Content — bottom-left */}
      <motion.div
        style={{ opacity: contentOpacity, y: contentY }}
        className="relative z-10 w-full max-w-[1500px] mx-auto px-6 md:px-16 lg:px-24 pb-20 md:pb-28"
      >
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.9, delay: 0.3, ease: easeQuiet }}
          className="flex items-center gap-5 mb-6 md:mb-10"
        >
          <span className="block w-11 h-px bg-gold/70" />
          <span className="text-gold tracking-[0.42em] text-[10px] md:text-[11px] font-medium uppercase">
            Neos
          </span>
          <span className="text-gold/45 font-serif italic text-sm md:text-base">adj. new</span>
        </motion.div>

        <div className="overflow-hidden pb-2 md:pb-4">
          <motion.h1
            initial={{ y: '105%' }}
            animate={{ y: 0 }}
            transition={{ duration: 1.1, delay: 0.5, ease: easeQuiet }}
            className="font-serif font-normal text-white leading-[0.95] text-[clamp(2.5rem,min(13vh,11vw),9.5rem)]"
            style={{ letterSpacing: '-0.04em' }}
          >
            Partner early.
          </motion.h1>
        </div>
        <div className="overflow-hidden pb-2 md:pb-4">
          <motion.h1
            initial={{ y: '105%' }}
            animate={{ y: 0 }}
            transition={{ duration: 1.1, delay: 0.65, ease: easeQuiet }}
            className="font-serif italic font-normal text-gold leading-[0.95] text-[clamp(2.5rem,min(13vh,11vw),9.5rem)]"
            style={{ letterSpacing: '-0.04em' }}
          >
            Build better.
          </motion.h1>
        </div>

        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 1.05, ease: easeQuiet }}
          className="mt-8 max-w-xl text-base md:text-lg text-white/70 leading-[1.7] font-light"
        >
          A new way to build. Neos connects Nations, contractors, and owners through strategic planning and efficient execution.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 1.2, ease: easeQuiet }}
          className="mt-8 flex flex-col sm:flex-row gap-8 sm:gap-14 items-start"
        >
          <a href="#contact" className="group inline-flex items-center gap-3 text-white">
            <span className="relative pb-1.5 text-sm md:text-base tracking-[0.18em] uppercase font-medium">
              Start a conversation
              <span className="absolute left-0 bottom-0 h-px w-full bg-gold/70 origin-left transition-transform duration-500 group-hover:scale-x-110" />
            </span>
            <ArrowUpRight
              size={18}
              className="text-gold transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1"
            />
          </a>
          <a
            href="#services"
            className="group inline-flex items-center gap-3 text-white/70 transition-colors duration-500 hover:text-white"
          >
            <span className="text-sm md:text-base tracking-[0.18em] uppercase font-medium">
              What we do
            </span>
            <ArrowRight
              size={18}
              className="text-gold/70 transition-all duration-500 group-hover:translate-x-1 group-hover:text-gold"
            />
          </a>
        </motion.div>
      </motion.div>
    </section>
  );
};

export default HeroAtelier;
